//GROUP 10
//2017A7PS0179P - MAYANK JAIN
//2017A7PS0143P - UJJWAL GANDHI
//2017A7PS0157P - ADITYA MITHAL
//2017A7PS0101P - ATMADEEP BANERJEE

#ifndef astDef_h
#define astDef_h

#include "parserDef.h"
#include "lexerDef.h"

#define LABELSIZE 20

// typedef union attributeType;
//enum type {INTEGER,REAL,BOOLEAN};

extern int ASTNODES;
extern char* nodeNameString[];
enum nodeName {BOOLEAN_NODE, REAL_NODE, INTEGER_NODE, INPUTPLIST_HEADER_NODE, RET_HEADER_NODE, MODULEDEF_HEADER_NODE, MODULEDEC_HEADER_NODE, OTHERMOD_HEADER_NODE, DRIVER_MOD_NODE, TRUE_NODE, FALSE_NODE, NUM_NODE, RNUM_NODE, ID_NODE, PLUS_NODE, MINUS_NODE, MUL_NODE, DIV_NODE, AND_NODE, OR_NODE, LT_NODE, LE_NODE, GT_NODE, GE_NODE, EQ_NODE, NE_NODE, PROGRAM_NODE, MODULE_NODE, DATATYPE_ARRAY_NODE, RANGEARRAYS_NODE, MODULEREUSESTMT_NODE, GET_STMT_NODE, PRINT_STMT_NODE, VARIDNUM_NODE, ASSIGNOP_NODE, ASSIGNOP_ARRAY_NODE, ID_ARRAY_NODE, U_NODE, DECLARESTMT_NODE, CONDITIONALSTMT_NODE, FORITERATIVESTMT_NODE, WHILEITERATIVESTMT_NODE, RANGE_NODE, RELATIONALOP_NODE, LOGICALOP_NODE,IDLIST_NODE, OPTIONAL_RETURN_NODE, INPUTPLIST_NODE, CASESTMTS_HEADER_NODE};

enum dataTypes {BOOL, FLOAT, INT};
extern int DATA_TYPE_SIZES[];

typedef struct ASTnode{
    int label;
    int isLeaf;
    struct ASTnode* firstChild;
    struct ASTnode* sibling;
    struct ASTnode* parent;
    int numberChildren;
    ptree_node* syntaxTreeNode;
}ASTnode;

#endif
